# Generated by Django 5.0.1 on 2024-04-05 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("login_send_credentials", "Login - send credentials"),
                            ("appointment_created", "Appointment - created"),
                            ("appointment_updated", "Appointment - updated"),
                            ("appointment_rescheduled", "Appointment - rescheduled"),
                            ("appointment_canceled", "Appointment canceled"),
                            ("invoice_expired", "Invoice expired"),
                            ("invoice_created", "Invoice created"),
                        ],
                        default="normal",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                ("content", models.TextField(blank=True, null=True)),
                ("is_read", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "receiver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
