# Generated by Django 5.0.1 on 2024-04-17 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0003_alter_notification_event"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ("-created",)},
        ),
    ]
