# Generated by Django 5.0.1 on 2024-04-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0004_alter_notification_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="metadata",
            field=models.JSONField(blank=True, default="{}", null=True),
        ),
    ]
