# Generated by Django 5.0.1 on 2024-04-17 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0005_notification_metadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
