# Generated by Django 5.0.1 on 2024-04-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0007_attachmentfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachmentfile",
            name="size",
            field=models.IntegerField(default=0),
        ),
    ]
