# Generated by Django 5.0.1 on 2024-04-18 13:10

import system.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0008_attachmentfile_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachmentfile",
            name="file",
            field=models.FileField(upload_to=system.models.get_directory_path),
        ),
    ]
