# Generated by Django 5.0.1 on 2024-04-23 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0010_attachmentfile_tag_alter_notification_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachmentfile",
            name="tag",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
    ]
