# Generated by Django 5.0.1 on 2024-04-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0011_alter_attachmentfile_tag"),
    ]

    operations = [
        migrations.CreateModel(
            name="DBSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("option_name", models.CharField(max_length=255, unique=True)),
                ("option_value", models.CharField(blank=True, default="")),
                (
                    "option_type",
                    models.CharField(
                        choices=[
                            ("str", "string"),
                            ("int", "integer"),
                            ("float", "float"),
                            ("bool", "boolean"),
                        ],
                        default="str",
                    ),
                ),
            ],
        ),
    ]
