# Generated by Django 5.0.1 on 2024-04-24 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0012_dbsettings"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dbsettings",
            options={"ordering": ("id",), "verbose_name": "DB Setting"},
        ),
    ]
