# Generated by Django 5.0.1 on 2024-04-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0013_alter_dbsettings_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Expence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                ("desc", models.TextField(blank=True, default="", null=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
