# Generated by Django 5.0.1 on 2024-05-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0015_rename_expence_expense"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="attachments_ids",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
