# Generated by Django 5.0.1 on 2024-05-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0017_rename_attachments_ids_expense_attachment_ids"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attachmentfile",
            options={"ordering": ("-created",)},
        ),
        migrations.AlterField(
            model_name="attachmentfile",
            name="created",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="attachmentfile",
            name="is_used",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
