# Generated by Django 5.0.1 on 2024-05-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0018_alter_attachmentfile_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="tax",
            field=models.FloatField(default=0),
        ),
    ]
