# Generated by Django 5.0.1 on 2024-05-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0020_expense_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="event",
            field=models.CharField(
                choices=[
                    ("normal", "Normal"),
                    ("login_send_credentials", "Login - send credentials"),
                    ("appointment_created", "Appointment - created"),
                    ("appointment_updated", "Appointment - updated"),
                    ("appointment_rescheduled", "Appointment - rescheduled"),
                    ("appointment_canceled", "Appointment canceled"),
                    ("invoice_expired", "Invoice expired"),
                    ("invoice_created", "Invoice created"),
                    ("progress_report_available", "Progress Report Available"),
                    ("progress_report_created", "Progress Report Created"),
                    ("medication_time", "Medication Time"),
                    ("contract_reminder", "Contract Reminder"),
                ],
                default="normal",
            ),
        ),
    ]
