# Generated by Django 5.0.1 on 2024-05-28 13:39

import system.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0021_alter_notification_event"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProtectedEmail",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(blank=True, max_length=255, null=True)),
                ("content", models.TextField(blank=True, null=True)),
                (
                    "expired_at",
                    models.DateTimeField(
                        default=system.models.get_expiration_date,
                        help_text="The date when the email will expire",
                    ),
                ),
                ("passkey", models.CharField(default="", max_length=30)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
