# Generated by Django 5.0.1 on 2024-05-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0023_protectedemail_email_type_protectedemail_metadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protectedemail",
            name="email_type",
            field=models.CharField(
                choices=[
                    ("incident_report", "Incident Report"),
                    ("medical_report", "Medical Report"),
                    ("progress_report", "Progress Report"),
                ]
            ),
        ),
    ]
