# Generated by Django 5.0.1 on 2024-01-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_clientdetails_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdiagnosis',
            name='date_of_diagnosis',
            field=models.DateField(auto_now_add=True),
        ),
    ]
