# Generated by Django 5.0.1 on 2024-02-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_clientdocuments_original_filename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdiagnosis',
            name='date_of_diagnosis',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
