# Generated by Django 5.0.1 on 2024-02-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_alter_clientdiagnosis_date_of_diagnosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdocuments',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
