# Generated by Django 5.0.1 on 2024-02-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0011_clientdocuments_file_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="progressreport",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
