# Generated by Django 5.0.1 on 2024-02-06 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0013_clientemergencycontact_auto_reports"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProgressReport",
        ),
    ]
