# Generated by Django 5.0.1 on 2024-02-07 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0014_delete_progressreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='client',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='client',
        ),
        migrations.RemoveField(
            model_name='observations',
            name='client',
        ),
        migrations.RemoveField(
            model_name='physicalstate',
            name='client',
        ),
        migrations.DeleteModel(
            name='EmotionalState',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='Measurement',
        ),
        migrations.DeleteModel(
            name='Observations',
        ),
        migrations.DeleteModel(
            name='PhysicalState',
        ),
    ]
