# Generated by Django 5.0.1 on 2024-02-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0016_clientdetails_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientemergencycontact",
            name="relation_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PrimaryRelationship", "Primary-Relationship"),
                    ("SecondaryRelationship", "Secondary-Relationship"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
