# Generated by Django 5.0.1 on 2024-02-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0017_alter_clientemergencycontact_relation_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientemergencycontact",
            name="relation_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Primary-Relationship", "Primary Relationship"),
                    ("Secondary-Relationship", "Secondary Relationship"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
