# Generated by Django 5.0.1 on 2024-03-04 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0027_clienttype_client"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clienttype",
            name="client",
        ),
    ]
