# Generated by Django 5.0.1 on 2024-03-04 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0028_remove_clienttype_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientsentby', to='client.clientdetails')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientsender', to='client.clienttype')),
            ],
        ),
    ]
