# Generated by Django 5.0.1 on 2024-03-05 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0029_clientsender"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientdetails",
            name="sender",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clientsender",
                to="client.clienttype",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="ClientSender",
        ),
    ]
