# Generated by Django 5.0.1 on 2024-03-07 15:34

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0033_remove_contract_end_date_contract_duration_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemporaryFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("file", models.FileField(upload_to="temporary_files/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name="contract",
            old_name="duration",
            new_name="duration_client",
        ),
        migrations.AddField(
            model_name="contract",
            name="duration_sender",
            field=models.IntegerField(null=True, verbose_name="Times per Year"),
        ),
    ]
