# Generated by Django 5.0.1 on 2024-03-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0036_alter_invoice_vat_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienttype',
            name='email_adress',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
