# Generated by Django 5.0.1 on 2024-03-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0037_clienttype_email_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
