# Generated by Django 5.0.1 on 2024-03-13 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0038_invoice_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="clientdetails",
            name="user",
            field=models.OneToOneField(
                default=5,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Client_Profile",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
