# Generated by Django 5.0.1 on 2024-03-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0039_clientdetails_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('bank_transfer', 'Bank Transfer'), ('credit_card', 'Credit Card'), ('check', 'Check'), ('cash', 'Cash')], max_length=50, null=True),
        ),
    ]
