# Generated by Django 5.0.1 on 2024-03-15 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_location'),
        ('client', '0040_invoice_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetails',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_location', to='authentication.location'),
        ),
    ]
