# Generated by Django 5.0.1 on 2024-03-18 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0041_alter_clientdetails_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_invoice', to='client.clientdetails'),
        ),
        migrations.CreateModel(
            name='InvoiceContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_vat_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_invoice', to='client.contract')),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_contract', to='client.invoice')),
            ],
        ),
    ]
