# Generated by Django 5.0.1 on 2024-03-25 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0043_invoice_invoice_details_alter_invoice_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_details',
        ),
    ]
