# Generated by Django 5.0.1 on 2024-03-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0044_remove_invoice_invoice_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="invoice_details",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
