# Generated by Django 5.0.1 on 2024-03-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0046_remove_clientemergencycontact_auto_reports_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='careplanatachements',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
