# Generated by Django 5.0.1 on 2024-03-28 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0047_careplanatachements_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careplanatachements',
            name='careplan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='care_attachement', to='client.careplan'),
        ),
    ]
