# Generated by Django 5.0.1 on 2024-04-03 08:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0048_alter_careplanatachements_careplan"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="invoice",
            name="updated",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddField(
            model_name="invoicecontract",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="invoicecontract",
            name="updated",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
