# Generated by Django 5.0.1 on 2024-04-04 15:58

import client.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0049_invoice_created_invoice_updated_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="temporaryfile",
            name="id",
            field=models.CharField(
                default=client.models.generate_invoice_id,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
