# Generated by Django 5.0.1 on 2024-04-08 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0003_alter_assessment_domain"),
        ("client", "0050_alter_temporaryfile_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="careplan",
            name="domains",
            field=models.ManyToManyField(
                related_name="care_plans", to="assessments.assessmentdomain"
            ),
        ),
    ]
