# Generated by Django 5.0.1 on 2024-04-17 09:31

import client.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0052_contracttype_contract_contract_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="invoice_number",
            field=models.CharField(
                default=client.models.generate_invoice_id,
                editable=False,
                max_length=10,
                unique=True,
            ),
        ),
    ]
