# Generated by Django 5.0.1 on 2024-04-17 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0053_alter_invoice_invoice_number"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ClientType",
            new_name="Sender",
        ),
        migrations.RenameModel(
            old_name="ClientTypeContactRelation",
            new_name="SenderContactRelation",
        ),
    ]
