# Generated by Django 5.0.1 on 2024-04-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0054_rename_clienttype_sender_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invoice",
            options={"ordering": ("-created",)},
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="client",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="payment_type",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="pre_vat_total",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="url",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="vat_amount",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="vat_rate",
        ),
        migrations.AddField(
            model_name="invoice",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("bank_transfer", "Bank Transfer"),
                    ("credit_card", "Credit Card"),
                    ("check", "Check"),
                    ("cash", "Cash"),
                ],
                default="credit_card",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="invoice",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="invoice_details",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("outstanding", "Outstanding"),
                    ("partially_paid", "Partially Paid"),
                    ("paid", "Paid"),
                    ("expired", "Expired"),
                    ("overpaid", "Overpaid"),
                    ("imported", "Imported"),
                    ("concept", "Concept"),
                ],
                default="concept",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
