# Generated by Django 5.0.1 on 2024-04-17 17:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0055_alter_invoice_options_remove_invoice_client_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contract",
            name="contract_type",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="duration_client",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="duration_sender",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="rate_type",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="rate_value",
        ),
        migrations.AddField(
            model_name="contract",
            name="care_name",
            field=models.CharField(default="Care Service 1", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contract",
            name="end_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contract",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contract",
            name="price_frequency",
            field=models.CharField(
                choices=[
                    ("hourly", "Hourly"),
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                ],
                default="weekly",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="reminder_period",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="contract",
            name="tax",
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="tax_exempltion",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contract",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="client.contracttype",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="contract",
            name="care_type",
            field=models.CharField(
                choices=[("\u200bambulante", "Ambulante"), ("accommodation", "Accommodation")]
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="client.clientdetails"
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="created",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contract",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="client.sender",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="start_date",
            field=models.DateTimeField(),
        ),
    ]
