# Generated by Django 5.0.1 on 2024-04-17 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0056_remove_contract_contract_type_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contract",
            old_name="tax_exempltion",
            new_name="tax_exemption",
        ),
    ]
