# Generated by Django 5.0.1 on 2024-04-18 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0057_rename_tax_exempltion_contract_tax_exemption"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contract",
            options={"ordering": ("-created",)},
        ),
        migrations.AddField(
            model_name="invoice",
            name="client",
            field=models.ForeignKey(
                default=11, on_delete=django.db.models.deletion.CASCADE, to="client.clientdetails"
            ),
            preserve_default=False,
        ),
    ]
