# Generated by Django 5.0.1 on 2024-04-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0058_alter_contract_options_invoice_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="price_frequency",
            field=models.CharField(
                choices=[
                    ("minute", "Minute"),
                    ("hourly", "Hourly"),
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                ],
                default="weekly",
            ),
        ),
    ]
