# Generated by Django 5.0.1 on 2024-04-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0059_alter_contract_price_frequency"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="attachment_ids",
            field=models.JSONField(default=list),
        ),
    ]
