# Generated by Django 5.0.1 on 2024-04-19 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0060_contract_attachment_ids"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contract",
            name="tax_exemption",
        ),
    ]
