# Generated by Django 5.0.1 on 2024-04-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0061_remove_contract_tax_exemption"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="status",
            field=models.CharField(
                choices=[
                    ("approved", "Approved"),
                    ("draft", "Draft"),
                    ("terminated", "Terminated"),
                ],
                default="draft",
            ),
        ),
    ]
