# Generated by Django 5.0.1 on 2024-04-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0062_contract_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="care_type",
            field=models.CharField(
                choices=[("ambulante", "Ambulante"), ("accommodation", "Accommodation")]
            ),
        ),
    ]
