# Generated by Django 5.0.1 on 2024-04-23 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0063_alter_contract_care_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="hours",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="contract",
            name="hours_type",
            field=models.CharField(
                choices=[("weekly", "Weekly"), ("all_period", "All Period")], default="all_period"
            ),
        ),
    ]
