# Generated by Django 5.0.1 on 2024-04-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0064_contract_hours_contract_hours_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("bank_transfer", "Bank Transfer"),
                    ("credit_card", "Credit Card"),
                    ("check", "Check"),
                    ("cash", "Cash"),
                ],
                null=True,
            ),
        ),
    ]
