# Generated by Django 5.0.1 on 2024-04-23 15:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0065_alter_invoice_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=20),
        ),
    ]
