# Generated by Django 5.0.1 on 2024-04-24 14:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0068_clientstatushistory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clientstatushistory",
            options={"ordering": ("-start_date",)},
        ),
        migrations.CreateModel(
            name="ContractWorkingHours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("hours", models.IntegerField(default=0)),
                (
                    "datetime",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="working_hours",
                        to="client.contract",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contract Working Hours",
                "verbose_name_plural": "Contract Working Hours",
                "ordering": ("datetime",),
            },
        ),
    ]
