# Generated by Django 5.0.1 on 2024-04-24 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0069_alter_clientstatushistory_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contractworkinghours",
            old_name="hours",
            new_name="minutes",
        ),
    ]
