# Generated by Django 5.0.1 on 2024-04-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0070_rename_hours_contractworkinghours_minutes"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractworkinghours",
            name="notes",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
