# Generated by Django 5.0.1 on 2024-04-26 08:43

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0071_contractworkinghours_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="total_paid_amount",
            field=models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=20),
        ),
        migrations.CreateModel(
            name="InvoiceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("bank_transfer", "Bank Transfer"),
                            ("credit_card", "Credit Card"),
                            ("check", "Check"),
                            ("cash", "Cash"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=20),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="client.invoice",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Invoice history",
                "ordering": ("-created",),
            },
        ),
    ]
