# Generated by Django 5.0.1 on 2024-04-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0072_invoice_total_paid_amount_invoicehistory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="payment_method",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="total_paid_amount",
        ),
        migrations.AlterField(
            model_name="invoicehistory",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("bank_transfer", "Bank Transfer"),
                    ("credit_card", "Credit Card"),
                    ("check", "Check"),
                    ("cash", "Cash"),
                    ("other", "Other"),
                ],
                null=True,
            ),
        ),
    ]
