# Generated by Django 5.0.1 on 2024-04-26 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0073_remove_invoice_payment_method_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarePlanGoals",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("desc", models.TextField(blank=True, default="", null=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "care_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals",
                        to="client.careplan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CarePlanObjectives",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("desc", models.TextField(blank=True, default="", null=True)),
                ("rating", models.FloatField(default=0)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="objectives",
                        to="client.careplangoals",
                    ),
                ),
            ],
        ),
    ]
