# Generated by Django 5.0.1 on 2024-04-26 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0003_alter_assessment_domain"),
        ("client", "0075_rename_careplangoals_careplangoal_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CarePlanGoal",
            new_name="DomainGoal",
        ),
        migrations.RenameModel(
            old_name="CarePlanObjective",
            new_name="DomainObjective",
        ),
        migrations.AlterField(
            model_name="domaingoal",
            name="care_plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goals",
                to="assessments.assessmentdomain",
            ),
        ),
    ]
