# Generated by Django 5.0.1 on 2024-04-26 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0076_rename_careplangoal_domaingoal_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="domaingoal",
            old_name="care_plan",
            new_name="domain",
        ),
    ]
