# Generated by Django 5.0.1 on 2024-04-27 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0003_alter_assessment_domain"),
        ("client", "0078_alter_contract_status_alter_invoice_invoice_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="domaingoal",
            name="client",
            field=models.ForeignKey(
                default=11,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goals",
                to="client.clientdetails",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="domaingoal",
            name="domain",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="goals",
                to="assessments.assessmentdomain",
            ),
        ),
    ]
