# Generated by Django 5.0.1 on 2024-04-27 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0079_domaingoal_client_alter_domaingoal_domain"),
    ]

    operations = [
        migrations.AddField(
            model_name="domainobjective",
            name="client",
            field=models.ForeignKey(
                default=11,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="objectives",
                to="client.clientdetails",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="domainobjective",
            name="goal",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="objectives",
                to="client.domaingoal",
            ),
        ),
    ]
