# Generated by Django 5.0.1 on 2024-04-28 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0080_domainobjective_client_alter_domainobjective_goal"),
        ("system", "0015_rename_expence_expense"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="pdf_attachment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="system.attachmentfile",
            ),
        ),
    ]
