# Generated by Django 5.0.1 on 2024-04-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0081_invoice_pdf_attachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientdetails",
            name="identity_attachment_ids",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="contract",
            name="attachment_ids",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
