# Generated by Django 5.0.1 on 2024-04-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0082_clientdetails_identity_attachment_ids_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="financing_acts",
            field=models.CharField(
                choices=[
                    ("WMO", "WMO"),
                    ("ZVW", "ZVW"),
                    ("WLZ", "WLZ"),
                    ("JW", "JW"),
                    ("WPG", "WPG"),
                ],
                default="WMO",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="financing_options",
            field=models.CharField(choices=[("ZIN", "ZIN"), ("ZVW", "ZVW")], default="ZVW"),
        ),
    ]
