# Generated by Django 5.0.1 on 2024-04-28 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0083_contract_financing_acts_contract_financing_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="financing_options",
            field=models.CharField(choices=[("ZIN", "ZIN"), ("PGB", "PGB")], default="PGB"),
        ),
        migrations.CreateModel(
            name="GoalHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("rating", models.FloatField(default=0)),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="client.domaingoal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ObjectiveHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("rating", models.FloatField(default=0)),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "objective",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="client.domainobjective",
                    ),
                ),
            ],
        ),
    ]
