# Generated by Django 5.0.1 on 2024-04-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0084_alter_contract_financing_options_goalhistory_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goalhistory",
            name="date",
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="objectivehistory",
            name="date",
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
    ]
