# Generated by Django 5.0.1 on 2024-04-28 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0003_alter_assessment_domain"),
        ("client", "0085_alter_goalhistory_date_alter_objectivehistory_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="careplan",
            name="client",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="care_plans",
                to="client.clientdetails",
            ),
        ),
        migrations.CreateModel(
            name="ClientCurrentLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("level", models.FloatField(default=1)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="current_levels",
                        to="client.clientdetails",
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="current_levels",
                        to="assessments.assessmentdomain",
                    ),
                ),
            ],
        ),
    ]
