# Generated by Django 5.0.1 on 2024-04-30 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0087_rename_financing_acts_contract_financing_act_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="status",
            field=models.CharField(
                choices=[
                    ("approved", "Approved"),
                    ("draft", "Draft"),
                    ("terminated", "Terminated"),
                    ("stopped", "Stopped"),
                ],
                default="draft",
            ),
        ),
        migrations.CreateModel(
            name="ClientState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("value", models.IntegerField(default=0)),
                (
                    "type",
                    models.CharField(
                        choices=[("emotional", "Emotional"), ("physical", "Physical")]
                    ),
                ),
                ("content", models.TextField(default="", null=True)),
                ("update", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_states",
                        to="client.clientdetails",
                    ),
                ),
            ],
        ),
    ]
