# Generated by Django 5.0.1 on 2024-04-30 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0088_alter_contract_status_clientstate"),
    ]

    operations = [
        migrations.RenameField(
            model_name="clientstate",
            old_name="update",
            new_name="updated",
        ),
    ]
