# Generated by Django 5.0.1 on 2024-04-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0089_rename_update_clientstate_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientcurrentlevel",
            name="level",
            field=models.IntegerField(default=1),
        ),
    ]
