# Generated by Django 5.0.1 on 2024-05-01 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0090_alter_clientcurrentlevel_level"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="domainobjective",
            name="goal",
        ),
        migrations.RemoveField(
            model_name="goalhistory",
            name="goal",
        ),
        migrations.RemoveField(
            model_name="domainobjective",
            name="client",
        ),
        migrations.RemoveField(
            model_name="objectivehistory",
            name="objective",
        ),
        migrations.DeleteModel(
            name="DomainGoal",
        ),
        migrations.DeleteModel(
            name="GoalHistory",
        ),
        migrations.DeleteModel(
            name="DomainObjective",
        ),
        migrations.DeleteModel(
            name="ObjectiveHistory",
        ),
    ]
