# Generated by Django 5.0.1 on 2024-05-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0091_remove_domainobjective_goal_remove_goalhistory_goal_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="extra_content",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
