# Generated by Django 5.0.1 on 2024-05-02 12:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0092_invoice_extra_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientcurrentlevel",
            name="content",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="clientcurrentlevel",
            name="created",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
