# Generated by Django 5.0.1 on 2024-05-05 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0093_clientcurrentlevel_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="departure_reason",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="departure_report",
            field=models.TextField(null=True),
        ),
    ]
