# Generated by Django 5.0.1 on 2024-05-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0094_contract_departure_reason_contract_departure_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientdetails",
            name="departure_reason",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="clientdetails",
            name="departure_report",
            field=models.TextField(null=True),
        ),
    ]
