# Generated by Django 5.0.1 on 2024-05-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0095_clientdetails_departure_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientdetails",
            name="gps_position",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="clientdetails",
            name="departure_reason",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="clientdetails",
            name="departure_report",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contract",
            name="departure_reason",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="contract",
            name="departure_report",
            field=models.TextField(blank=True, null=True),
        ),
    ]
