# Generated by Django 5.0.1 on 2024-05-20 09:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0097_alter_clientdetails_options_alter_contract_hours"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="careplan",
            options={"ordering": ("-id",)},
        ),
        migrations.AlterField(
            model_name="temporaryfile",
            name="id",
            field=models.CharField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
