# Generated by Django 5.0.1 on 2024-05-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0099_clientdocuments_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientdocuments",
            name="label",
            field=models.CharField(
                choices=[
                    ("registration_form", "Registration Form"),
                    ("intake_form", "Intake Form"),
                    ("consent_form", "Consent Form"),
                    ("risk_assessment", "Risk Assessment"),
                    ("self_reliance_matrix", "Self-reliance Matrix"),
                    ("force_inventory", "Force Inventory"),
                    ("care_plan", "Care Plan"),
                    ("signaling_plan", "Signaling Plan"),
                    ("cooperation_agreement", "Cooperation Agreement"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=100,
            ),
        ),
    ]
