# Generated by Django 5.0.1 on 2024-05-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0100_alter_clientdocuments_label"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("soft_delete", models.BooleanField(default=False)),
            ],
        ),
    ]
