# Generated by Django 5.0.1 on 2024-05-24 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0009_location_capacity"),
        ("client", "0101_contactrelationship"),
    ]

    operations = [
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("employee_fullname", models.CharField(max_length=100)),
                ("employee_position", models.CharField(max_length=100)),
                (
                    "reporter_involvement",
                    models.CharField(
                        choices=[
                            ("directly_involved", "Directly involved"),
                            ("witness", "Witness"),
                            ("found_afterwards", "Found afterwards"),
                            ("alarmed", "Alarmed"),
                        ],
                        max_length=100,
                    ),
                ),
                ("inform_who", models.JSONField(default=list)),
                ("incident_date", models.DateField()),
                ("runtime_incident", models.CharField(max_length=100)),
                ("incident_type", models.CharField(max_length=100)),
                ("passing_away", models.BooleanField(default=False)),
                ("self_harm", models.BooleanField(default=False)),
                ("violence", models.BooleanField(default=False)),
                ("fire_water_damage", models.BooleanField(default=False)),
                ("accident", models.BooleanField(default=False)),
                ("client_absence", models.BooleanField(default=False)),
                ("medicines", models.BooleanField(default=False)),
                ("organization", models.BooleanField(default=False)),
                ("use_prohibited_substances", models.BooleanField(default=False)),
                ("other_notifications", models.BooleanField(default=False)),
                (
                    "severity_of_incident",
                    models.CharField(
                        choices=[
                            ("near_incident", "Near Incident"),
                            ("less_serious", "Less Serious"),
                            ("serious", "Serious"),
                            ("fatal", "Fatal"),
                        ],
                        max_length=100,
                    ),
                ),
                ("incident_explanation", models.TextField(blank=True, null=True)),
                (
                    "recurrence_risk",
                    models.CharField(
                        choices=[
                            ("very_low", "Very Low"),
                            ("means", "Means"),
                            ("high", "High"),
                            ("very_high", "Very High"),
                        ],
                        max_length=100,
                    ),
                ),
                ("incident_prevent_steps", models.TextField(blank=True, null=True)),
                ("incident_taken_measures", models.TextField(blank=True, null=True)),
                ("technical", models.JSONField(default=list)),
                ("organizational", models.JSONField(default=list)),
                ("mese_worker", models.JSONField(default=list)),
                ("client", models.JSONField(default=list)),
                ("cause_explanation", models.TextField(blank=True, default="", null=True)),
                (
                    "physical_injury",
                    models.CharField(
                        choices=[
                            ("no_injuries", "No Injuries"),
                            ("not_noticeable_yet", "Not Noticeable Yet"),
                            ("bruising_swelling", "Bruising/Swelling"),
                            ("skin_injury", "Skin Injury"),
                            ("broken_bones", "Broken Bones"),
                            ("shortness_of_breath", "Shortness of Breath"),
                            ("death", "Death"),
                            ("other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                ("physical_injury_desc", models.TextField(blank=True, default="", null=True)),
                (
                    "psychological_damage",
                    models.CharField(
                        choices=[
                            ("no", "No"),
                            ("not_noticeable_yet", "Not Noticeable Yet"),
                            ("drowsiness", "Drowsiness"),
                            ("unrest", "Unrest"),
                        ],
                        max_length=100,
                    ),
                ),
                ("psychological_damage_desc", models.TextField(blank=True, default="", null=True)),
                (
                    "needed_consultation",
                    models.CharField(
                        choices=[
                            ("no", "No"),
                            ("not_clear", "Not Clear Yet"),
                            ("hospitalization", "Hospitalization"),
                            ("consult_gp", "Consult GP"),
                        ],
                        max_length=100,
                    ),
                ),
                ("succession", models.JSONField(default=list)),
                ("succession_desc", models.TextField(blank=True, default="", null=True)),
                ("other", models.BooleanField(default=False)),
                ("other_desc", models.CharField(blank=True, max_length=100, null=True)),
                ("additional_appointments", models.TextField(blank=True, default="", null=True)),
                ("employee_absenteeism", models.JSONField(default=list)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "location",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incident",
                        to="authentication.location",
                    ),
                ),
            ],
        ),
    ]
