# Generated by Django 5.0.1 on 2024-05-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0103_alter_incident_client"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="incident",
            options={"ordering": ("-created",)},
        ),
        migrations.AddField(
            model_name="incident",
            name="soft_delete",
            field=models.BooleanField(default=False),
        ),
    ]
