# Generated by Django 5.0.1 on 2024-05-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0105_incident_client_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="other_cause",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
