# Generated by Django 5.0.1 on 2024-05-27 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0106_incident_other_cause"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollaborationAgreements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("client_full_name", models.CharField(max_length=100)),
                ("client_SKN", models.CharField(max_length=100)),
                ("client_number", models.CharField(max_length=100)),
                ("client_phone", models.CharField(max_length=100)),
                ("probation_full_name", models.CharField(max_length=100)),
                ("probation_organization", models.CharField(max_length=100)),
                ("probation_phone", models.CharField(max_length=100)),
                ("healthcare_institution_name", models.CharField(max_length=100)),
                ("healthcare_institution_organization", models.CharField(max_length=100)),
                ("healthcare_institution_phone", models.CharField(max_length=100)),
                ("healthcare_institution_function", models.CharField(max_length=100)),
                ("contact_agreements", models.TextField()),
                ("attention_risks", models.JSONField(default=list)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collaboration_agreements",
                        to="client.clientdetails",
                    ),
                ),
            ],
        ),
    ]
