# Generated by Django 5.0.1 on 2024-05-27 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0107_collaborationagreements"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CollaborationAgreements",
            new_name="CollaborationAgreement",
        ),
    ]
