# Generated by Django 5.0.1 on 2024-05-27 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0108_rename_collaborationagreements_collaborationagreement"),
    ]

    operations = [
        migrations.CreateModel(
            name="RiskAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date_of_birth", models.DateField()),
                ("gender", models.CharField(max_length=100)),
                ("date_of_intake", models.DateTimeField()),
                ("intaker_position_name", models.CharField(max_length=100)),
                ("family_situation", models.TextField()),
                ("education_work", models.TextField()),
                ("current_living_situation", models.TextField()),
                ("social_network", models.TextField()),
                ("previous_assistance", models.TextField()),
                ("behaviour_at_school_work", models.TextField()),
                ("people_skills", models.TextField()),
                ("emotional_status", models.TextField()),
                ("self_image_self_confidence", models.TextField()),
                ("stress_factors", models.TextField()),
                ("committed_offences_description", models.TextField()),
                ("offences_frequency_seriousness", models.TextField()),
                ("age_first_offense", models.TextField()),
                ("circumstances_surrounding_crimes", models.TextField()),
                ("offenses_recations", models.TextField()),
                ("personal_risk_factors", models.TextField()),
                ("environmental_risk_factors", models.TextField()),
                ("behaviour_recurrence_risk", models.TextField()),
                ("abuse_substance_risk", models.TextField()),
                ("person_strengths", models.TextField()),
                ("positive_influences", models.TextField()),
                ("available_support_assistance", models.TextField()),
                ("person_strategies", models.TextField()),
                ("specific_needs", models.TextField()),
                ("recommended_interventions", models.TextField()),
                ("other_agencies_involvement", models.TextField()),
                ("risk_management_plan_of_actions", models.TextField()),
                ("findings_summary", models.TextField()),
                ("institution_advice", models.TextField()),
                ("inclusion", models.TextField()),
                ("intaker_name", models.CharField(max_length=100)),
                ("report_date", models.DateField()),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_assessments",
                        to="client.clientdetails",
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
    ]
