# Generated by Django 5.0.1 on 2024-05-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0109_riskassessment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='psychological_damage',
            field=models.CharField(choices=[('no', 'No'), ('not_noticeable_yet', 'Not Noticeable Yet'), ('drowsiness', 'Drowsiness'), ('unrest', 'Unrest'), ('other', 'Other')], max_length=100),
        ),
    ]
