# Generated by Django 5.0.1 on 2024-05-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0111_riskassessment_regular_evaluation_plan_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsentDeclaration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("youth_name", models.CharField(max_length=255)),
                ("date_of_birth", models.DateField()),
                ("parent_guardian_name", models.CharField(max_length=255)),
                ("address", models.TextField()),
                ("youth_care_institution", models.CharField(max_length=255)),
                ("proposed_assistance_description", models.TextField()),
                ("statement_by_representative", models.TextField()),
                ("parent_guardian_signature_date", models.DateField()),
                ("juvenile_name", models.CharField(blank=True, max_length=255, null=True)),
                ("juvenile_signature_date", models.DateField(blank=True, null=True)),
                ("representative_name", models.CharField(max_length=255)),
                ("representative_signature_date", models.DateField()),
                ("contact_person_name", models.CharField(max_length=255)),
                ("contact_phone_number", models.CharField(max_length=20)),
                ("contact_email", models.EmailField(max_length=254)),
            ],
        ),
    ]
