# Generated by Django 5.0.1 on 2024-05-29 15:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0112_consentdeclaration"),
    ]

    operations = [
        migrations.AddField(
            model_name="consentdeclaration",
            name="created",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="consentdeclaration",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
