# Generated by Django 5.0.1 on 2024-05-29 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0113_consentdeclaration_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="consentdeclaration",
            name="client",
            field=models.ForeignKey(
                default=11,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consent_declarations",
                to="client.clientdetails",
            ),
            preserve_default=False,
        ),
    ]
