# Generated by Django 5.0.1 on 2024-05-31 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0114_consentdeclaration_client"),
    ]

    operations = [
        migrations.CreateModel(
            name="YouthCareIntake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Man"), ("V", "Vrouw"), ("A", "Anders")], max_length=1
                    ),
                ),
                ("nationality", models.CharField(max_length=100)),
                ("bsn", models.CharField(max_length=20)),
                ("address", models.TextField()),
                ("postcode", models.CharField(max_length=20)),
                ("residence", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("referrer_name", models.CharField(max_length=255)),
                ("referrer_organization", models.CharField(max_length=255)),
                ("referrer_function", models.CharField(max_length=255)),
                ("referrer_phone_number", models.CharField(max_length=20)),
                ("referrer_email", models.EmailField(max_length=254)),
                (
                    "service_choice",
                    models.CharField(
                        choices=[
                            ("outpatient_care", "Outpatient care"),
                            ("sheltered_housing", "Sheltered housing"),
                            ("assisted_living", "Assisted Living"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "financing_form",
                    models.CharField(
                        choices=[
                            ("jeugdwet_zin", "Jeugdwet ZIN"),
                            ("pgb_jeugdwet", "PGB Jeugdwet"),
                            ("wlz_pgb", "WLZ PGB"),
                            ("otherwise", "Otherwise"),
                        ],
                        max_length=20,
                    ),
                ),
                ("financing_other", models.CharField(blank=True, max_length=255, null=True)),
                ("registration_reason", models.TextField()),
                ("current_situation_background", models.TextField()),
                ("previous_aid_agencies_involved", models.BooleanField(default=False)),
                ("previous_aid_agencies_details", models.TextField(blank=True, null=True)),
                ("medical_conditions", models.BooleanField(default=False)),
                ("medical_conditions_details", models.TextField(blank=True, null=True)),
                ("medication_use", models.BooleanField(default=False)),
                ("medication_details", models.TextField(blank=True, null=True)),
                ("allergies_or_dietary_needs", models.BooleanField(default=False)),
                ("allergies_or_dietary_details", models.TextField(blank=True, null=True)),
                ("addictions", models.BooleanField(default=False)),
                ("addictions_details", models.TextField(blank=True, null=True)),
                ("school_or_daytime_activities", models.BooleanField(default=False)),
                ("school_daytime_name", models.CharField(blank=True, max_length=255, null=True)),
                ("current_class_level", models.CharField(blank=True, max_length=100, null=True)),
                ("school_contact_person", models.CharField(blank=True, max_length=255, null=True)),
                ("school_contact_phone", models.CharField(blank=True, max_length=20, null=True)),
                ("school_contact_email", models.EmailField(blank=True, max_length=254, null=True)),
                ("important_people", models.TextField(blank=True, null=True)),
                ("external_supervisors_involved", models.BooleanField(default=False)),
                ("external_supervisors_details", models.TextField(blank=True, null=True)),
                ("special_circumstances", models.TextField(blank=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
        migrations.AlterModelOptions(
            name="consentdeclaration",
            options={"ordering": ("-created",)},
        ),
    ]
