# Generated by Django 5.0.1 on 2024-05-31 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0116_remove_youthcareintake_financing_form_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="consentdeclaration",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
