# Generated by Django 5.0.1 on 2024-05-31 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0117_consentdeclaration_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="consentdeclaration",
            name="content",
        ),
    ]
