# Generated by Django 5.0.1 on 2024-05-31 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0118_remove_consentdeclaration_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientemergencycontact",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
