# Generated by Django 5.0.1 on 2024-05-31 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0119_clientemergencycontact_is_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientemergencycontact",
            name="uuid",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
