# Generated by Django 5.0.1 on 2024-05-31 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0121_datasharingstatement"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="datasharingstatement",
            name="juvenile_signature",
        ),
    ]
