# Generated by Django 5.0.1 on 2024-06-28 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0123_datasharingstatement_created_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sender",
            options={"ordering": ("-id",)},
        ),
    ]
