# Generated by Django 5.0.1 on 2024-07-08 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0010_remove_selectedmaturitymatrixassessment_maturitymatrix_and_more"),
        ("client", "0125_clientdetails_maturity_domains"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaturityMatrix",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_approved", models.BooleanField(default=False)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maturity_matrices",
                        to="client.clientdetails",
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="SelectedMaturityMatrixAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selected_assessments",
                        to="assessments.assessment",
                    ),
                ),
                (
                    "maturitymatrix",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selected_assessments",
                        to="client.maturitymatrix",
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
        migrations.AddField(
            model_name="maturitymatrix",
            name="assessments",
            field=models.ManyToManyField(
                through="client.SelectedMaturityMatrixAssessment", to="assessments.assessment"
            ),
        ),
    ]
