# Generated by Django 5.0.1 on 2024-07-10 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0125_clientdetails_maturity_domains'),
        ('system', '0024_alter_protectedemail_email_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborationagreement',
            name='pdf_attachment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.attachmentfile'),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='pdf_attachment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.attachmentfile'),
        ),
    ]
