# Generated by Django 5.0.1 on 2024-07-12 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0127_alter_riskassessment_pdf_attachment'),
        ('system', '0024_alter_protectedemail_email_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='consentdeclaration',
            name='pdf_attachment',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.attachmentfile'),
        ),
    ]
