# Generated by Django 5.0.1 on 2025-01-21 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0126_maturitymatrix_selectedmaturitymatrixassessment_and_more"),
        ("client", "0128_consentdeclaration_pdf_attachment"),
    ]

    operations = []
