version: '3.8'

services:
  web:
    image: healthy:latest
    user: ${UID:-1000}:${UID:-1000}
    build: .
    command: bash -c "daphne healty.asgi:application --bind 0.0.0.0 --port 8000"
    volumes:
      - ./:/healthy
    ports:
      - "8000:8000"
    depends_on:
      - celery
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/1
    networks:
      - public
      - private

  redis:
    image: "redis:alpine"
    networks:
      - private

  celery:
    build: .
    command: celery -A healty worker --loglevel=info
    volumes:
      - ./:/healthy
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/1

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - public
      - private

networks:
  public:
  private:
