version: '3.8'

services:
  web:
    image: 146023855582.dkr.ecr.eu-central-1.amazonaws.com/healthy:latest
    command: bash -c "daphne healty.asgi:application --bind 0.0.0.0 --port 8000"
    env_file:
      - .env
    networks:
      - public
      - private
    depends_on:
      - celery
      - redis

  redis:
    image: redis:alpine
    networks:
      - private

  celery:
    image: 146023855582.dkr.ecr.eu-central-1.amazonaws.com/my_celery:latest
    working_dir: /healthy
    command: celery -A healty.celery worker --beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    env_file:
      - .env
    networks:
      - private
    depends_on:
      - redis

  caddy:
    image: caddy:2
    ports:
      - 80:80
      - 443:443
    environment:
      DOMAIN_NAME: https://maicare.devteam.cc
      REVERSE_PROXY: web:8000
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - ./caddy/config:/config
    networks:
      - public
      - private

volumes:
  caddy_data:


networks:
  public:
  private:
