version: '3.8'

services:
  web:
    image: healthy:latest
    user: ${UID:-1000}:${UID:-1000}
    build: .
    command: bash -c "daphne healty.asgi:application --bind 0.0.0.0 --port 8000"
    volumes:
      - ./:/healthy
    environment:
      - REDIS_URL=redis://redis:6379/1
      - CELERY_BROKER_URL=redis://redis:6379
    ports:
      - "8000:8000"
    networks:
      - public
      - private
    depends_on:
      - celery
      - redis

  redis:
    image: redis:alpine
    networks:
      - private

  celery:
    image: my_celery:latest
    working_dir: /healthy
    user: ${UID:-1000}:${UID:-1000}
    build:
      context: .
      dockerfile: ./celery/Dockerfile
    command: celery -A healty.celery worker -l info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
    volumes:
      - ./:/healthy
    networks:
      - private
    depends_on:
      - redis

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - public
      - private

networks:
  public:
  private:
