version: "3.8"

services:
  backend: # default port is 8000
    image: ${AWS_REGISTRY}/healthy:latest
    command: bash -c "daphne healty.asgi:application --bind 0.0.0.0 --port 8000"
    env_file:
      - .env
    networks:
      - public
      - private
    depends_on:
      - celery
      - redis

  frontend: # default port is 3000
    image: ${AWS_REGISTRY}/maicare-frontend:latest
    environment:
      # Connect the fontend to the backend
      NEXT_PUBLIC_WS_URL: wss://maicare-api.devteam.cc/ws/
      NEXT_PUBLIC_API_URL: https://maicare-api.devteam.cc
    networks:
      - public
    depends_on:
      - backend

  redis:
    image: redis:alpine
    networks:
      - private

  celery:
    image: ${AWS_REGISTRY}/healthy:latest
    working_dir: /healthy
    command: celery -A healty.celery worker --beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    env_file:
      - .env
    networks:
      - private
    depends_on:
      - redis

  caddy:
    image: caddy:2
    ports:
      - 80:80
      - 443:443
    environment:
      FRONTEND_DOMAIN_NAME: https://maicare.devteam.cc
      FRONTEND_SERVER: frontend:3000

      BACKEND_DOMAIN_NAME: https://maicare-api.devteam.cc
      BACKEND_SERVER: backend:8000
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - ./caddy/config:/config
    networks:
      - public
      - private

volumes:
  caddy_data:

networks:
  public:
  private:
