version: "3.8"

services:
  backend:
    image: ${AWS_REGISTRY}/healthy:latest
    command: bash -c "daphne healty.asgi:application --bind 0.0.0.0 --port 8000"
    env_file:
      - .env
    networks:
      - public
      - private
    depends_on:
      - celery
      - redis

  frontend:
    image: ${AWS_REGISTRY}/maicare-frontend:latest
    ports:
      - 3000:3000
    environment:
      # Connect the fontend to the backend
      NEXT_PUBLIC_WS_URL: wss://backend:8000/ws/
      NEXT_PUBLIC_API_URL: http://backend:8000/
    networks:
      - public
    depends_on:
      - backend

  redis:
    image: redis:alpine
    networks:
      - private

  celery:
    image: ${AWS_REGISTRY}/healthy:latest
    working_dir: /healthy
    command: celery -A healty.celery worker --beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    env_file:
      - .env
    networks:
      - private
    depends_on:
      - redis

  caddy:
    image: caddy:2
    ports:
      - 80:80
      - 443:443
    environment:
      DOMAIN_NAME: https://maicare.devteam.cc
      REVERSE_PROXY: frontend:3000
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - ./caddy/config:/config
    networks:
      - public
      - private

volumes:
  caddy_data:

networks:
  public:
  private:
