version: "3.8"

services:
  web:
    image: healthy:latest
    user: ${UID:-1000}:${UID:-1000}
    build: .
    ports:
      - "8000:8000"
    command: bash -c "make serve"
    volumes:
      - ./:/healthy

  celery:
    image: healthy:latest
#    working_dir: /healthy
    user: ${UID:-1000}:${UID:-1000}
    command: celery -A healty.celery worker --beat -l DEBUG --scheduler django_celery_beat.schedulers:DatabaseScheduler
    # build:
    #   context: .
    #   dockerfile: ./celery/Dockerfile
    volumes:
      - ./:/healthy
