version: '3.8'

services:
  web:
    image: 146023855582.dkr.ecr.eu-central-1.amazonaws.com/healthy:latest
    command: bash -c "daphne healty.asgi:application --bind 0.0.0.0 --port 8000"
    env_file:
      - .env
    networks:
      - public
      - private
    depends_on:
      - celery
      - redis

  redis:
    image: redis:alpine
    networks:
      - private

  celery:
    image: 146023855582.dkr.ecr.eu-central-1.amazonaws.com/my_celery:latest
    working_dir: /healthy
    command: celery -A healty.celery worker -l info
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
    networks:
      - private
    depends_on:
      - redis

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - public
      - private

networks:
  public:
  private:
