version: '3.8'

services:
  web:
    image: 146023855582.dkr.ecr.eu-central-1.amazonaws.com/healthy:latest
    command: bash -c "daphne healty.asgi:application --bind 0.0.0.0 --port 8000"
    env_file:
      - .env
    networks:
      - public
      - private
    depends_on:
      - celery
      - redis

  redis:
    image: redis:alpine
    networks:
      - private

  celery:
    image: 146023855582.dkr.ecr.eu-central-1.amazonaws.com/my_celery:latest
    working_dir: /healthy
    command: celery -A healty.celery worker -l info
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
    networks:
      - private
    depends_on:
      - redis

  caddy:
    image: caddy:2
    ports:
      - 80:80
      - 443:443
    environment:
      DOMAIN_NAME: https://maicare.devteam.cc
      REVERSE_PROXY: web:8000
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/data:/data
    networks:
      - public
      - private

networks:
  public:
  private:
