version: '3.8'

services:
  web:
    image: healthy:latest
    user: ${UID:-1000}:${UID:-1000}
    build: .
    command: bash -c "daphne healty.asgi:application --bind 0.0.0.0 --port 8000"
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/1

  redis:
    image: "redis:alpine"

  celery:
    build: .
    command: celery -A healty worker --loglevel=info
    volumes:
      - .:/usr/src/app
    depends_on:
      - web
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/1

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro

    depends_on:
      - web
      - celery

