# Generated by Django 5.0.1 on 2024-04-06 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0002_alter_assessment_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessment",
            name="domain",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessments",
                to="assessments.assessmentdomain",
            ),
        ),
    ]
