# Generated by Django 5.0.1 on 2024-06-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0003_alter_assessment_domain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessment",
            name="content",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
