# Generated by Django 5.0.1 on 2024-07-01 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0004_alter_assessment_content"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assessment",
            options={"ordering": ("level",)},
        ),
    ]
