# Generated by Django 5.0.1 on 2024-07-04 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0007_alter_maturitymatrix_client"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="maturitymatrix",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="maturity_matrices",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
