# Generated by Django 5.0.1 on 2024-07-08 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "assessments",
            "0009_rename_maturity_matrix_selectedmaturitymatrixassessment_maturitymatrix",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="selectedmaturitymatrixassessment",
            name="maturitymatrix",
        ),
        migrations.RemoveField(
            model_name="selectedmaturitymatrixassessment",
            name="assessment",
        ),
        migrations.DeleteModel(
            name="MaturityMatrix",
        ),
    ]
