# Generated by Django 5.0.1 on 2024-07-08 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0010_remove_selectedmaturitymatrixassessment_maturitymatrix_and_more"),
        ("employees", "0065_alter_domaingoal_selected_maturity_matrix_assessment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SelectedMaturityMatrixAssessment",
        ),
    ]
