# Generated by Django 5.0.1 on 2024-02-02 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_assignment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employeeprofile",
            name="address",
        ),
        migrations.RemoveField(
            model_name="employeeprofile",
            name="date_of_birth",
        ),
        migrations.RemoveField(
            model_name="employeeprofile",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="employeeprofile",
            name="last_name",
        ),
    ]
