# Generated by Django 5.0.1 on 2024-02-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_progressreport_author_progressreport_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='highest_education',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
