# Generated by Django 5.0.1 on 2024-02-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0011_alter_feedback_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="observations",
            name="category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
