# Generated by Django 5.0.1 on 2024-02-12 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0014_employeeprofile_authentication_phone_number_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employeeprofile",
            old_name="private_email_adress",
            new_name="private_email_address",
        ),
    ]
