# Generated by Django 5.0.1 on 2024-02-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0015_rename_private_email_adress_employeeprofile_private_email_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeprofile",
            name="gender",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="home_telephone_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="is_subcontractor",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
