# Generated by Django 5.0.1 on 2024-02-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0016_employeeprofile_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
