# Generated by Django 5.0.1 on 2024-03-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0021_clientmedication"),
    ]

    operations = [
        migrations.AlterField(
            model_name="progressreport",
            name="created",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
