# Generated by Django 5.0.1 on 2024-03-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0023_clientgoals"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientgoals",
            name="report",
            field=models.TextField(blank=True, null=True),
        ),
    ]
