# Generated by Django 5.0.1 on 2024-03-08 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0026_goalsreport_delete_temporaryfile_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="goalsreport",
            old_name="tiltle",
            new_name="title",
        ),
    ]
