# Generated by Django 5.0.1 on 2024-03-15 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0007_location"),
        ("employees", "0027_rename_tiltle_goalsreport_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeprofile",
            name="location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employee_location",
                to="authentication.location",
            ),
        ),
    ]
