# Generated by Django 5.0.1 on 2024-04-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0034_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='event',
            field=models.CharField(choices=[('normal', 'Normal')], default='normal'),
        ),
    ]
