# Generated by Django 5.0.1 on 2024-04-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0035_notification_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="event",
            field=models.CharField(
                choices=[
                    ("normal", "Normal"),
                    ("login_send_credentials", "Login - send credentials"),
                    ("appointment_created", "Appointment - created"),
                    ("appointment_updated", "Appointment - updated"),
                    ("appointment_rescheduled", "Appointment - rescheduled"),
                ],
                default="normal",
            ),
        ),
    ]
