# Generated by Django 5.0.1 on 2024-04-05 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0037_alter_notification_event"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
