# Generated by Django 5.0.1 on 2024-04-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0038_delete_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientmedication",
            name="days",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="clientmedication",
            name="times",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="clientmedication",
            name="updated",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="clientmedication",
            name="created",
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
    ]
