# Generated by Django 5.0.1 on 2024-04-15 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0039_clientmedication_days_clientmedication_times_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientmedication",
            name="is_critical",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="ClientMedicationRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_taken", models.BooleanField(blank=True, default=False, null=True)),
                ("reason", models.TextField(blank=True, null=True)),
                ("time", models.DateTimeField(db_index=True)),
                ("updated", models.DateTimeField(auto_now=True, db_index=True)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "client_medication_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="employees.clientmedication",
                    ),
                ),
            ],
        ),
    ]
