# Generated by Django 5.0.1 on 2024-04-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0040_clientmedication_is_critical_clientmedicationrecord"),
    ]

    operations = [
        migrations.RenameField(
            model_name="clientmedicationrecord",
            old_name="client_medication_id",
            new_name="client_medication",
        ),
        migrations.RemoveField(
            model_name="clientmedicationrecord",
            name="is_taken",
        ),
        migrations.AddField(
            model_name="clientmedicationrecord",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("taken", "Taken"), ("not_taken", "Not Taken"), ("awaiting", "Awaiting")],
                default="awaiting",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="clientmedicationrecord",
            name="reason",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
