# Generated by Django 5.0.1 on 2024-04-15 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "employees",
            "0041_rename_client_medication_id_clientmedicationrecord_client_medication_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clientmedication",
            name="frequency",
        ),
    ]
