# Generated by Django 5.0.1 on 2024-04-15 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0042_remove_clientmedication_frequency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientmedication",
            name="administered_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medications_administered",
                to="employees.employeeprofile",
            ),
        ),
    ]
