# Generated by Django 5.0.1 on 2024-04-16 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0043_alter_clientmedication_administered_by"),
    ]

    operations = [
        migrations.RenameField(
            model_name="clientmedication",
            old_name="days",
            new_name="slots",
        ),
        migrations.RemoveField(
            model_name="clientmedication",
            name="times",
        ),
    ]
