# Generated by Django 5.0.1 on 2024-04-17 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0044_rename_days_clientmedication_slots_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clientmedication",
            options={"ordering": ("-created",)},
        ),
        migrations.AlterModelOptions(
            name="clientmedicationrecord",
            options={"ordering": ("-created",)},
        ),
    ]
