# Generated by Django 5.0.1 on 2024-04-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0045_alter_clientmedication_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="progressreport",
            name="type",
            field=models.CharField(
                choices=[
                    ("morning_report", "Morning report"),
                    ("evening_report", "Evening report"),
                    ("night_report", "Night report"),
                    ("shift_report", "Intermediate shift report"),
                    ("one_to_one_report", "1 on 1 Reporting"),
                    ("process_report", "Process Reporting"),
                    ("contact_journal", "Contact Journal"),
                    ("other", "Other"),
                ],
                default="other",
            ),
        ),
    ]
