# Generated by Django 5.0.1 on 2024-05-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0047_domaingoal_domainobjective_goalhistory_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="domaingoal",
            options={"ordering": ("-created",)},
        ),
        migrations.AddField(
            model_name="objectivehistory",
            name="content",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
