# Generated by Django 5.0.1 on 2024-05-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0048_alter_domaingoal_options_objectivehistory_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="objectivehistory",
            name="week",
            field=models.IntegerField(db_index=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="objectivehistory",
            unique_together={("week", "objective")},
        ),
    ]
