# Generated by Django 5.0.1 on 2024-05-03 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0049_objectivehistory_week_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="objectivehistory",
            options={"ordering": ("week",)},
        ),
    ]
