# Generated by Django 5.0.1 on 2024-05-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminmodif", "0005_permission_group_permissions"),
        ("employees", "0050_alter_objectivehistory_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeprofile",
            name="groups",
            field=models.ManyToManyField(to="adminmodif.group"),
        ),
    ]
