# Generated by Django 5.0.1 on 2024-05-05 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminmodif", "0005_permission_group_permissions"),
        ("employees", "0051_employeeprofile_groups"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employeeprofile",
            name="groups",
        ),
        migrations.CreateModel(
            name="Access",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("start_date", models.DateTimeField(null=True)),
                ("end_date", models.DateTimeField(null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="employees.employeeprofile"
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="adminmodif.group"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="group_access",
            field=models.ManyToManyField(through="employees.Access", to="adminmodif.group"),
        ),
    ]
