# Generated by Django 5.0.1 on 2024-05-05 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminmodif", "0005_permission_group_permissions"),
        ("employees", "0052_remove_employeeprofile_groups_access_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("start_date", models.DateTimeField(null=True)),
                ("end_date", models.DateTimeField(null=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="employees.employeeprofile"
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="adminmodif.group"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="employeeprofile",
            name="group_access",
            field=models.ManyToManyField(through="employees.GroupAccess", to="adminmodif.group"),
        ),
        migrations.DeleteModel(
            name="Access",
        ),
    ]
