# Generated by Django 5.0.1 on 2024-05-05 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0053_groupaccess_alter_employeeprofile_group_access_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employeeprofile",
            old_name="group_access",
            new_name="groups",
        ),
    ]
