# Generated by Django 5.0.1 on 2024-05-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0054_rename_group_access_employeeprofile_groups"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="groupaccess",
            options={"ordering": ("-created",)},
        ),
        migrations.AlterField(
            model_name="groupaccess",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="groupaccess",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
