# Generated by Django 5.0.1 on 2024-05-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0055_alter_groupaccess_options_alter_groupaccess_end_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employeeprofile",
            options={"ordering": ("-id",)},
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="out_of_service",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
