# Generated by Django 5.0.1 on 2024-05-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0056_alter_employeeprofile_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeprofile",
            name="is_archived",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="employeeprofile",
            name="out_of_service",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
