# Generated by Django 5.0.1 on 2024-05-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0057_employeeprofile_is_archived_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="progressreport",
            options={"ordering": ("-date",)},
        ),
        migrations.AddField(
            model_name="progressreport",
            name="emotional_state",
            field=models.CharField(
                choices=[
                    ("normal", "Normal"),
                    ("excited", "Excited"),
                    ("happy", "Happy"),
                    ("sad", "Sad"),
                    ("angry", "Angry"),
                    ("anxious", "Anxious"),
                    ("depressed", "Depressed"),
                    ("other", "Other"),
                ],
                default="normal",
            ),
        ),
    ]
