# Generated by Django 5.0.1 on 2024-06-25 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0123_datasharingstatement_created_and_more"),
        ("employees", "0062_objectiveprogressreport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="progressreport",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progress_reports",
                to="client.clientdetails",
            ),
        ),
    ]
