# Generated by Django 5.0.1 on 2024-07-04 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0006_maturitymatrix_selectedmaturitymatrixassessment_and_more"),
        ("employees", "0063_alter_progressreport_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="domaingoal",
            name="selected_maturity_matrix_assessment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goals",
                to="assessments.selectedmaturitymatrixassessment",
            ),
        ),
    ]
