# Generated by Django 5.0.1 on 2024-07-08 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0126_maturitymatrix_selectedmaturitymatrixassessment_and_more"),
        ("employees", "0064_domaingoal_selected_maturity_matrix_assessment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domaingoal",
            name="selected_maturity_matrix_assessment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goals",
                to="client.selectedmaturitymatrixassessment",
            ),
        ),
    ]
