# Generated by Django 5.0.1 on 2024-02-21 09:57

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0002_alter_appointment_clients"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemporaryFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("file", models.FileField(upload_to="temporary_files/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
