# Generated by Django 5.0.1 on 2024-05-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0006_alter_appointment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="appointment_type",
            field=models.CharField(
                choices=[
                    ("meeting", "Meeting"),
                    ("work", "Work with Client"),
                    ("home_care", "Home Care"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
