# Generated by Django 5.0.1 on 2024-06-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0008_alter_appointment_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="temporary_file_ids",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
