# Generated by Django 5.0.1 on 2024-03-14 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_alter_customuser_phone_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("adress", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="customuser",
            name="location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="location",
                to="authentication.location",
            ),
        ),
        migrations.DeleteModel(
            name="adresses",
        ),
    ]
