# Generated by Django 5.0.1 on 2024-03-15 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_location_customuser_location_delete_adresses"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="location",
        ),
        migrations.DeleteModel(
            name="Location",
        ),
    ]
