# Generated by Django 5.0.1 on 2024-03-13 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adminmodif", "0003_group_alter_groupmembership_group"),
    ]

    operations = [
        migrations.RenameField(
            model_name="group",
            old_name="group_name",
            new_name="name",
        ),
    ]
