# Generated by Django 5.0.1 on 2024-05-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminmodif", "0004_rename_group_name_group_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="group",
            name="permissions",
            field=models.ManyToManyField(blank=True, to="adminmodif.permission"),
        ),
    ]
