# Generated by Django 5.0.1 on 2024-05-06 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adminmodif", "0005_permission_group_permissions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="group",
            options={"ordering": ("-id",)},
        ),
    ]
