# Generated by Django 5.0.1 on 2024-05-06 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIGeneratedReports",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("client_profile_summary", "Client Profile Summary"),
                            (
                                "client_goals_and_objectives_summary",
                                "Client goals and objective summary",
                            ),
                            ("employee_performance", "Employee Performance"),
                        ]
                    ),
                ),
                ("content", models.TextField(blank=True, null=True)),
                (
                    "user_type",
                    models.CharField(choices=[("client", "Client"), ("employee", "Employee")]),
                ),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True, db_index=True)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
