# Generated by Django 5.0.1 on 2024-05-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aigeneratedreports",
            name="title",
            field=models.CharField(default=11, max_length=255),
            preserve_default=False,
        ),
    ]
