# Generated by Django 5.0.1 on 2024-05-06 12:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0002_aigeneratedreports_title"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AIGeneratedReports",
            new_name="AIGeneratedReport",
        ),
    ]
