# Generated by Django 5.0.1 on 2024-05-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0003_rename_aigeneratedreports_aigeneratedreport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aigeneratedreport",
            name="report_type",
            field=models.CharField(
                choices=[
                    ("client_reports_summary", "Client reports Summary"),
                    ("client_profile_summary", "Client Profile Summary"),
                    ("client_goals_and_objectives_summary", "Client goals and objective summary"),
                    ("employee_performance", "Employee Performance"),
                ]
            ),
        ),
    ]
