# Generated by Django 5.0.1 on 2024-05-08 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0004_alter_aigeneratedreport_report_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aigeneratedreport",
            options={"ordering": ("-created",)},
        ),
    ]
